### ISSUE TITLE
Type Error: list indices must be integers,not numpy.string_

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [periakiva/Bag-of-Words#1]
I have a problem when I run the predit.py:

       predictions = [classlist[i] for i in clf.predict(testfeatures)]
       
in this line, it says:
       Type Error: list indices must be integers,not numpy.string_

**Comment by periakiva** [comment]
Try to print "i" and see if its a number. it might be that "i" is a number but in a string type so you can convert it by switching to:

   predictions = [classlist[int(i)] for i in clf.predict(testfeatures)]

If "i" is a string label you will have to change it to:

   predictions = [i for i in clf.predict(testfeatures)]

Since it's an old project I don't remember the data types I used but make sure they stay consistent throughout.
